version: '3.8'
services:
  eventstore:
    image: mongo
    hostname: eventstore
    # command: ["--replSet", "rs01", "--bind_ip_all"]
    # healthcheck:
    #   test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongo) -eq 1
    #   interval: 10s
    #   start_period: 30s
    volumes:
      - events:/data/db
  
  eventbus:
    image: nats-streaming

  product:
    depends_on:
      - eventstore
      - eventbus
    image: ecommerce_product
    environment:
      NATS_URL: nats://eventbus:4222
      MONGO_URL: mongodb://eventstore:27017
  
  order:
    depends_on:
      - eventstore
      - eventbus
    image: ecommerce_order
    environment:
      NATS_URL: nats://eventbus:4222
      MONGO_URL: mongodb://eventstore:27017
  
  stock:
    depends_on:
      - eventstore
      - eventbus
    image: ecommerce_stock
    environment:
      NATS_URL: nats://eventbus:4222
      MONGO_URL: mongodb://eventstore:27017

  cli:
    depends_on:
      - eventstore
      - eventbus
    image: ecommerce_cli
    environment:
      NATS_URL: nats://eventbus:4222
      MONGO_URL: mongodb://eventstore:27017
    tty: true

volumes:
  events:
