version: '3.8'
services:
  eventstore:
    hostname: eventstore
    image: mongo
    command: ["--quiet", "--logpath", "/dev/null", "--replSet", "rs01", "--bind_ip_all"]
    healthcheck:
      test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongo --quiet) -eq 1
      interval: 10s
      start_period: 30s
  
  eventbus:
    hostname: eventbus
    image: nats-streaming

  test:
    build:
      context: ../../..
      dockerfile: examples/ecommerce/.docker/test.Dockerfile
    environment:
      NATS_URL: nats://eventbus:4222
      MONGO_URL: mongodb://eventstore:27017
