version: '3.8'
services:
  nats:
    image: nats
  
  stan:
    image: nats-streaming

  mongostore:
    image: mongo
    command: ["--quiet", "--logpath", "/dev/null", "--bind_ip_all"]

  mongostore_replicaset:
    image: mongo
    command: ["--quiet", "--logpath", "/dev/null", "--replSet", "rs01", "--bind_ip_all"]
    healthcheck:
      test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongo --quiet) -eq 1
      interval: 10s
      start_period: 30s
  
  mongosnap:
    image: mongo
    command: ["--quiet", "--logpath", "/dev/null", "--bind_ip_all"]

  test:
    depends_on:
      - nats
      - stan
      - mongostore
      - mongostore_replicaset
      - mongosnap
    build:
      context: ..
      dockerfile: .docker/coverage.Dockerfile
      args:
        TAGS: nats,mongostore,mongosnap
    environment:
      - NATS_URL=nats://nats:4222
      - STAN_URL=nats://stan:4222
      - MONGOSTORE_URL=mongodb://mongostore:27017
      - MONGOREPLSTORE_URL=mongodb://mongostore_replicaset:27017
      - MONGOSNAP_URL=mongodb://mongosnap:27017
    volumes:
      - ../out:/coverage/out
