version: '3.8'
services:
  test:
    depends_on:
      - nats
      - stan
      - mongostore
      - mongosnap
    build:
      context: ..
      dockerfile: .docker/coverage.Dockerfile
      args:
        TAGS: nats,mongostore,mongosnap
    environment:
      - NATS_URL=nats://nats:4222
      - STAN_URL=nats://stan:4222
      - MONGOSTORE_URL=mongodb://mongostore:27017
      - MONGOSNAP_URL=mongodb://mongosnap:27017
    volumes:
      - ../out:/coverage/out
