version: '3.8'
services:
  nats:
    image: nats
  
  stan:
    image: nats-streaming

  mongo:
    image: mongo
    command: ["--quiet", "--logpath", "/dev/null", "--replSet", "rs01", "--bind_ip_all"]
    healthcheck:
      test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongo --quiet) -eq 1
      interval: 10s
      start_period: 30s
  
  test:
    depends_on:
      - nats
      - stan
      - mongo
    build:
      context: ..
      dockerfile: .docker/coverage.Dockerfile
      args:
        TAGS: nats,mongostore
    environment:
      - NATS_URL=nats://nats:4222
      - STAN_URL=nats://stan:4222
      - MONGO_URL=mongodb://mongo:27017
    volumes:
      - ../out:/coverage/out
