version: '3.8'
services:
  mongo:
    image: mongo
    command: --quiet --logpath /dev/null
  
  test:
    depends_on:
      - mongo
    build:
      context: ..
      dockerfile: .docker/tag-test.Dockerfile
      args:
        TAGS: mongostore
    environment:
      - MONGO_URL=mongodb://mongo:27017
