version: '3.8'
services:
  mongostore:
    image: mongo
    command: ["--quiet", "--logpath", "/dev/null", "--replSet", "rs01", "--bind_ip_all"]
    healthcheck:
      test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongo --quiet) -eq 1
      interval: 10s
      start_period: 30s
  
  mongosnap:
    image: mongo
    command: ["--quiet", "--logpath", "/dev/null", "--replSet", "rs01", "--bind_ip_all"]
    healthcheck:
      test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongo --quiet) -eq 1
      interval: 10s
      start_period: 30s

  test:
    depends_on:
      - mongostore
      - mongosnap
    build:
      context: ..
      dockerfile: .docker/tag-test.Dockerfile
      args:
        TAGS: mongostore,mongosnap
    environment:
      - MONGOSTORE_URL=mongodb://mongostore:27017
      - MONGOSNAP_URL=mongodb://mongosnap:27017
