version: '3.8'
services:
  nats:
    image: nats
  
  stan:
    image: nats-streaming

  jetstream:
    image: nats
    command: ["-js"]
  
  test:
    depends_on:
      - nats
      - stan
      - jetstream
    build:
      context: ..
      dockerfile: .docker/tag-test.Dockerfile
      args:
        TAGS: nats
    environment:
      - NATS_URL=nats://nats:4222
      - STAN_URL=nats://stan:4222
      - JETSTREAM_URL=nats://jetstream:4222
