version: '3.8'
services:
  nats:
    image: nats
  
  test:
    depends_on:
      - nats
    build:
      context: ..
      dockerfile: .docker/nats-test.Dockerfile
    environment:
      - NATS_URL=nats://nats:4222
